echo -e "\e[1;34m_________________\e[0m"
echo -e "\e[1;34m/                 \\ \e[0m"
echo -e "\e[1;34m|  \e[1;37mWelcome, human.\e[0m\e[1;34m |\e[0m"
echo -e "\e[1;34m\\_________________/\e[0m"
echo -e "         \e[1;34m||\e[0m"
echo -e "         \e[1;34m||\e[0m"
echo -e "         \e[1;34m||\e[0m"
echo ""
echo -e "\e[1;37mAvailable Commands:\e[0m"
echo -e "\e[1;95m- run-sdweb:\e[0m      Run SD Web UI"
echo -e "\e[1;95m- run-roop:\e[0m       Run Roop script"
echo -e "\e[1;95m- run-syncthing:\e[0m  Run Syncthing script"
echo -e "\e[1;95m- kill-minutes:\e[0m   Stop & Delete pod after X minutes"
echo -e "\e[1;95m- stop-minutes:\e[0m   Stop pod after X minutes"
echo ""
echo -e "\e[1;37mDirectory Shortcuts:\e[0m"
echo -e "\e[1;95m- cd-sdweb:\e[0m       Go to SD Web UI folder"
echo -e "\e[1;95m- cd-roop:\e[0m        Go to Roop folder"
echo -e "\e[1;95m- cd-syncthing:\e[0m   Go to Syncthing folder"
echo ""
QUOTE="$(shuf -n 1 /tmp/random_banner.txt)"
echo -e "\e[1;34m$QUOTE\e[0m \e[1;31m<3\e[1;37m Marv\e[0m"
echo ""
echo ""
